### PR TITLE
https nub

### PR DESCRIPTION
**Pull request by andrejsavikin**

### CODE REVIEW

**Comment by maxpowa** [comment]
Except hummingbird HTTPS calls SSL error.

**Comment by andrejsavikin** [comment]
Works fine for me, huh?

**Comment by maxpowa** [comment]
it's cause the SSL lib they are using dropped support for tlsv1 and that's what py 2.7 uses by default

**Comment by andrejsavikin** [comment]
So you still haven't updated to tslv2/3?

**Pull request closed without merging**
